### ISSUE TITLE
Documentação - Criar Tabela de Decisão

### ISSUE THREAD

**Issue by islansilva** [Biz1999/clean-arch-movie-categories#16]

**Comment by Biz1999** [comment]
Levantamento dos tabelas de decisão executado e documentado na [wiki de buscar categorias](https://github.com/Biz1999/clean-arch-movie-categories/wiki/UC002-%7C-Casos-de-Teste-%7C-Buscar-todas-as-categorias), e na aba [cadastro de categorias](https://github.com/Biz1999/clean-arch-movie-categories/wiki/UC001-%7C-Casos-de-Teste-%7C-Cadastrar-categoria)
